---
- name: Add TF GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add TF Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ lsb_release }} main
    state: present

- name: Update apt and install TF
  apt:
    pkg:
      - terraform
    state: latest
    update_cache: true
  register: terraform_ins_output
- debug: var=terraform_ins_output

